# Should we include this file in submission?
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score
from scipy.stats import pearsonr

# Load the data from CSV
# muscle-development.csv and hormones.csv are generated by NetLogo
df_tm = pd.read_csv('muscle-development.csv')
df_th = pd.read_csv('hormones.csv')
df_t = pd.merge(df_tm, df_th)

df_p = pd.read_csv('model_data.csv')


for name in ['muscle', 'anabolic', 'catabolic']:
    true_values = df_t[name]
    predicted_values = df_p[name]

    # Calculate RMSE
    rmse = np.sqrt(mean_squared_error(true_values, predicted_values))
    print(f"{name} RMSE: {round(rmse, 4)}")

    # Calculate R-squared
    r_squared = r2_score(true_values, predicted_values)
    print(f"{name} R-squared: {round(r_squared, 4)}")

    # Calculate Correlation Coefficient
    correlation_coefficient, _ = pearsonr(true_values, predicted_values)
    print(f"{name} Correlation Coefficient: {round(correlation_coefficient, 4)}")
